"""empty message

Revision ID: 9690d2729a3d
Revises: 
Create Date: 2019-08-09 13:09:49.335538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9690d2729a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    clientes_table = op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    seed_cliente_data(clientes_table)
    produtos_table = op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('multiplo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    seed_produto_data(produtos_table)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('rentabilidade', sa.String(), nullable=False),
    sa.Column('pedidos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedidos_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def seed_cliente_data(clientes_table):
    op.bulk_insert(
        clientes_table,
        [
            {
                'nome': 'Darth Vader'
            },
            {
                'nome': 'Obi-Wan Kenobi'
            },
            {
                'nome': 'Luke Skywalker'
            },
            {
                'nome': 'Imperador Palpatine'
            },
            {
                'nome': 'Han Solo'
            }
        ]
    )


def seed_produto_data(produtos_table):
    op.bulk_insert(
        produtos_table,
        [
            {
                'nome': 'Millenium Falcon',
                'preco_unitario': 550000,
                'multiplo': 1
            },
            {
                'nome': 'X-Wing',
                'preco_unitario': 60000,
                'multiplo': 2
            },
            {
                'nome': 'Super Star Destroyer',
                'preco_unitario': 4570000,
                'multiplo': 1
            },
            {
                'nome': 'TIE Fighter',
                'preco_unitario': 75000,
                'multiplo': 2
            },
            {
                'nome': 'Lightsaber',
                'preco_unitario': 6000,
                'multiplo': 5
            },
            {
                'nome': 'DLT-19 Heavy Blaster Rifle',
                'preco_unitario': 5800,
                'multiplo': 1
            },
            {
                'nome': 'DL-44 Heavy Blaster Pistol',
                'preco_unitario': 1500,
                'multiplo': 10
            }
        ]
    )
